# Generated by Django 2.2.7 on 2019-11-23 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=1024)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Compensation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('money', models.CharField(max_length=128)),
                ('requirements', models.TextField(max_length=2048)),
                ('additional_info', models.TextField(max_length=2048)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation', to='info.Category')),
            ],
        ),
    ]
