# Generated by Django 2.2.7 on 2019-11-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20191123_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compensation',
            name='once_a_term',
            field=models.BooleanField(default=False),
        ),
    ]
