# Generated by Django 2.2.7 on 2019-11-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20191123_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compensation',
            name='money',
            field=models.TextField(max_length=1024),
        ),
    ]
