# Generated by Django 2.2.7 on 2019-11-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20191123_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compensation',
            name='additional_info',
            field=models.TextField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='compensation',
            name='requirements',
            field=models.TextField(default='', max_length=2048),
        ),
    ]
