# Generated by Django 2.2.7 on 2019-11-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20191123_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compensation',
            name='additional_info',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='compensation',
            name='requirements',
            field=models.TextField(max_length=2048, null=True),
        ),
    ]
