# Generated by Django 2.2.7 on 2019-11-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_auto_20191123_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.CharField(default='', max_length=64),
        ),
    ]
