# Generated by Django 2.2.7 on 2019-11-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_category_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensation',
            name='url',
            field=models.CharField(default='', max_length=64),
        ),
    ]
