# Generated by Django 2.2.7 on 2019-11-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_auto_20191126_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensation',
            name='category_url',
            field=models.CharField(default='', max_length=64),
        ),
    ]
