# Generated by Django 2.2.7 on 2019-11-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_compensation_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.RemoveField(
            model_name='compensation',
            name='id',
        ),
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='compensation',
            name='url',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
