# Generated by Django 2.2.7 on 2019-12-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_compensation_category_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteListEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
