# Generated by Django 2.2.7 on 2019-11-26 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_auto_20191126_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='id',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='compensation',
            old_name='id',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='compensation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation', to='info.Category'),
        ),
    ]
