# Generated by Django 2.2.7 on 2019-12-16 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0014_auto_20191209_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compensation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensations', to='info.Category'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='compensation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensations', to='info.Compensation'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation', to='info.ValidatedStudent'),
        ),
    ]
