# Generated by Django 2.2.7 on 2019-11-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_auto_20191126_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensation',
            name='category_url',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.CharField(default='', max_length=64),
        ),
    ]
